name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: |
          curl -s --head https://trackifi.onrender.com > /dev/null
